[project]
name = "genx-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "loguru>=0.7.3",
    "pandas>=2.2.3",
    "universal-pathlib>=0.2.6",
    "xlwings>=0.33.14",
]
