# Gurobi Solver Parameters
Method: 2                     # Algorithm used to solve continuous models (including MIP root relaxation).
#Gurobi-specific solver settings
MIPGap: 1e-3                  # Relative (p.u. of optimal) mixed integer optimality tolerance for MIP problems (ignored otherwise).
BarConvTol: 1.0e-06           # Barrier convergence tolerance (determines when barrier terminates).
Crossover: 0                 # Barrier crossver strategy.
