NumStages: 3 # Number of model investment planning stages
StageLengths: [10,10,10] # Length of each model stage (years)
WACC: 0.045 # Weighted average cost of capital
ConvergenceTolerance: 0.01 # Relative optimality gap used for convergence
Myopic: 0 # If using multi-stage GenX, 1 = myopic, 0 = dual dynamic programming
DDP: 0 # 1 = DDP, 0 = monolithic multistage GenX
WriteIntermittentOutputs: 0 # If 1, write intermediate outputs to disk