NumStages: 3 # Number of model investment planning stages
StageLengths: [1,4,5] # Length of each model stage (years)
WACC: 0.045 # Weighted average cost of capital
ConvergenceTolerance: 0.01 # Relative optimality gap used for convergence
Myopic: 0 # If using multi-stage GenX, 1 = myopic, 0 = dual dynamic programming
WriteIntermittentOutputs: 1 # If 1, write intermediate outputs to disk